


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  INSERT INTO public."PROFILES" (email, project_list)
  VALUES (NEW.email, '{}'::bigint[]);
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."ANOMALIES" (
    "id" bigint NOT NULL,
    "step_name" "text" NOT NULL,
    "run_id" "text" NOT NULL,
    "project_id" bigint,
    "error_code" integer NOT NULL,
    "penalty_score" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."ANOMALIES" OWNER TO "postgres";


ALTER TABLE "public"."ANOMALIES" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."ANOMALIES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."CALLS" (
    "id" bigint NOT NULL,
    "step_name" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "model" "text",
    "prompt" "text",
    "input_tokens" bigint,
    "output_tokens" bigint DEFAULT '0'::bigint,
    "reasoning_tokens" bigint DEFAULT '0'::bigint,
    "total_tokens" bigint DEFAULT '0'::bigint,
    "latency_ms" bigint,
    "cost" real,
    "status_success" boolean,
    "error" "text",
    "output_code" "text",
    "run_id" "text" NOT NULL,
    "project_id" bigint,
    "parent_call_id" bigint,
    "step_index" integer
);

ALTER TABLE ONLY "public"."CALLS" REPLICA IDENTITY FULL;


ALTER TABLE "public"."CALLS" OWNER TO "postgres";


COMMENT ON TABLE "public"."CALLS" IS 'table storing logs of individual calls';



ALTER TABLE "public"."CALLS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."CALLS_run_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."PROFILES" (
    "id" bigint NOT NULL,
    "email" "text" DEFAULT 'NULL'::"text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "project_list" bigint[]
);


ALTER TABLE "public"."PROFILES" OWNER TO "postgres";


COMMENT ON TABLE "public"."PROFILES" IS 'user table';



ALTER TABLE "public"."PROFILES" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."PROFILES_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."PROJECTS" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "API_KEY" "text",
    "owner" bigint,
    "name" "text",
    "slack_webhook_url" "text",
    "alert_on_error" boolean DEFAULT true,
    "alert_error_rate_threshold" double precision DEFAULT 0.25,
    "alert_error_rate_window" integer DEFAULT 20,
    "sentry_dsn" "text",
    "sentry_alert_level" "text" DEFAULT 'critical'::"text",
    "slack_anomaly_level" "text" DEFAULT 'critical'::"text" NOT NULL,
    "threshold_mode" "text" DEFAULT 'dynamic'::"text" NOT NULL,
    "threshold_latency_ms" double precision,
    "threshold_tokens" double precision,
    "threshold_cost" double precision,
    "monthly_budget_usd" double precision
);


ALTER TABLE "public"."PROJECTS" OWNER TO "postgres";


COMMENT ON TABLE "public"."PROJECTS" IS 'stores the projects with their api keys and owners';



ALTER TABLE "public"."PROJECTS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."PROJECTS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."USAGE" (
    "id" bigint NOT NULL,
    "project_id" integer,
    "run_id" "text",
    "feature" "text" NOT NULL,
    "model" "text" NOT NULL,
    "input_tokens" integer DEFAULT 0 NOT NULL,
    "output_tokens" integer DEFAULT 0 NOT NULL,
    "cost_usd" double precision DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."USAGE" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."USAGE_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."USAGE_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."USAGE_id_seq" OWNED BY "public"."USAGE"."id";



ALTER TABLE ONLY "public"."USAGE" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."USAGE_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."ANOMALIES"
    ADD CONSTRAINT "ANOMALIES_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."CALLS"
    ADD CONSTRAINT "CALLS_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."PROFILES"
    ADD CONSTRAINT "PROFILES_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."PROJECTS"
    ADD CONSTRAINT "PROJECTS_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."USAGE"
    ADD CONSTRAINT "USAGE_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."CALLS"
    ADD CONSTRAINT "calls_step_run_unique" UNIQUE ("step_name", "run_id");



ALTER TABLE ONLY "public"."ANOMALIES"
    ADD CONSTRAINT "ANOMALIES_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."PROJECTS"("id");



ALTER TABLE ONLY "public"."CALLS"
    ADD CONSTRAINT "CALLS_parent_call_id_fkey" FOREIGN KEY ("parent_call_id") REFERENCES "public"."CALLS"("id");



ALTER TABLE ONLY "public"."USAGE"
    ADD CONSTRAINT "USAGE_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."PROJECTS"("id") ON DELETE CASCADE;



ALTER TABLE "public"."PROFILES" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."PROJECTS" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "anon can read" ON "public"."CALLS" FOR SELECT TO "anon" USING (true);



CREATE POLICY "users can read own profile" ON "public"."PROFILES" FOR SELECT USING (("email" = ("auth"."jwt"() ->> 'email'::"text")));



CREATE POLICY "users can update own profile" ON "public"."PROFILES" FOR UPDATE USING (("email" = ("auth"."jwt"() ->> 'email'::"text")));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."ANOMALIES";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."CALLS";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."PROJECTS";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";


















GRANT ALL ON TABLE "public"."ANOMALIES" TO "anon";
GRANT ALL ON TABLE "public"."ANOMALIES" TO "authenticated";
GRANT ALL ON TABLE "public"."ANOMALIES" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ANOMALIES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ANOMALIES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ANOMALIES_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."CALLS" TO "anon";
GRANT ALL ON TABLE "public"."CALLS" TO "authenticated";
GRANT ALL ON TABLE "public"."CALLS" TO "service_role";



GRANT ALL ON SEQUENCE "public"."CALLS_run_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."CALLS_run_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."CALLS_run_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."PROFILES" TO "anon";
GRANT ALL ON TABLE "public"."PROFILES" TO "authenticated";
GRANT ALL ON TABLE "public"."PROFILES" TO "service_role";



GRANT ALL ON SEQUENCE "public"."PROFILES_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."PROFILES_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."PROFILES_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."PROJECTS" TO "anon";
GRANT ALL ON TABLE "public"."PROJECTS" TO "authenticated";
GRANT ALL ON TABLE "public"."PROJECTS" TO "service_role";



GRANT ALL ON SEQUENCE "public"."PROJECTS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."PROJECTS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."PROJECTS_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."USAGE" TO "anon";
GRANT ALL ON TABLE "public"."USAGE" TO "authenticated";
GRANT ALL ON TABLE "public"."USAGE" TO "service_role";



GRANT ALL ON SEQUENCE "public"."USAGE_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."USAGE_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."USAGE_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































